#%RAML 1.0
title: Blog App REST API
version: v1
baseUrl: https://practitioner-blog-app-backend.herokuapp.com/
mediaType: application/json

securitySchemes:
  - oauth_2_0:
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization:
          description: Token de autorización
          type: string         
      responses:
        401:
          description: Token inválido o expirado

types:
  Post:
    type: object
    properties:
      title:
        type: string
        required: True
      author:
        type: string
        required: True
      content:
        type: string
        required: True
      categories:
        type: string[]
        required: True
      highlighted:
        type: boolean
  PostWithIdAndDates:
    type: Post
    properties:
      id:
        type: number
      created_at:
        type: string
      updated_at:
        type: string

/posts:
  get:
    description: Obtener una lista de todos los posts
    responses:
      200:
        body:
          type: PostWithIdAndDates[]
  post:
    description: Crear un nuevo post
    securedBy: [oauth_2_0]
    body:
      type: Post
    responses:
      201:
        body:
          type: PostWithIdAndDates
      422:
        description: Los datos enviados tienen errores
  /{id}:
    get:
      responses:
        200:
          body:
            type: PostWithIdAndDates
        404:
          description: El post solicitado no existe
    put:
      securedBy: [oauth_2_0]
      body:
        type: Post
      responses:
        200:
          body:
            type: PostWithIdAndDates
        404:
          description: El post solicitado no existe
        422:
          description: Los datos enviados tienen errores
    delete:
      securedBy: [oauth_2_0]
      responses:
        204:
          description: Post eliminado con éxito
        404:
          description: El post solicitado no existe
  
/auth:
  /login:
    post:
      body:
        type: object
        properties:
          username:
            type: string
          password:
            type: string
      responses:
        200:
          description: Login exitoso
          body:
            type: object
            properties:
              access_token:
                type: string
        401:
          description: Credenciales inválidas
